spring:
    datasource:
        hikari:
            jdbc-url: jdbc:h2:tcp://localhost/~/db_practice
            username: sa
            password: ""
            maximum-pool-size: 20

domain:
    allow-cors:
        localhost: http://localhost:8080
    