spring:
    datasource:
        hikari:
            jdbc-url: jdbc:h2:tcp://localhost/~/db_practice
            username: sa
            password: ""
            maximum-pool-size: 20
    jpa:
        open-in-view: false

domain:
    allow-cors:
        localhost: http://localhost:8080

jwt:
    accessTokenSecret: "mfoa)29afas!@fdASF3e"
    refreshTokenSecret: "1892ka09vm/$@!adsf@A32v"
    accessTokenLifetime: 1800000 # 30 min
    refreshTokenLifetime: 10800000 # 3 hour
    